[tool.poetry]
name = "smart-pju"
version = "0.1.0"
description = "PENGMAS TRI"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.scripts]
start = "src.main:main"
